name: Build and Sign APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-venv zip unzip openjdk-11-jdk libffi-dev libssl-dev libsqlite3-dev libbz2-dev libreadline-dev libncurses5-dev libgdbm-dev liblzma-dev autoconf automake libtool libtool-bin m4 build-essential git
        pip install --upgrade pip
        pip install cython "setuptools<60" buildozer

    - name: Restaurar keystore desde secreto
      run: |
        mkdir -p ~/.keystores
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ~/.keystores/my-release-key.keystore

    - name: Compilar APK en modo release
      run: |
        buildozer android release

    - name: Firmar APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore ~/.keystores/my-release-key.keystore \
          -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
          -keypass "${{ secrets.KEY_PASSWORD }}" \
          bin/*.apk "${{ secrets.KEY_ALIAS }}"

    - name: Subir APK firmado
      uses: actions/upload-artifact@v4
      with:
        name: llamadascontrol-release.apk
        path: bin/*.apk
